#FolderName
basefolder.name=ExtentReports/SparkReport_
basefolder.datetimepattern=d_MMM_YY HH_mm_ss

extent.reporter.spark.start=true
extent.reporter.spark.out=ExtentReports/HtmlReports/Spark.html
 
#PDF Report
extent.reporter.pdf.start=true
extent.reporter.pdf.out=PdfReport/ExtentPdf.pdf
 
#JSON Report
#extent.reporter.json.start=true
#extent.reporter.json.out=JsonReport/ExtentJson.json

 
#Screenshot
screenshot.dir=ExtentReports/HtmlReports/Screenshots/
screenshot.rel.path=./Screenshots/
 

 
